# NorTK custom dracut configuration
# Enables kiwi-live for overlayfs on Live ISO (flags=overlay)
add_dracutmodules+=" kiwi-live kiwi-overlay "
add_dracutmodules+=" plymouth "
install_optional_items+=" /usr/share/plymouth/themes/nortk/ "